### ISSUE TITLE
全消しと範囲消しについて

### ISSUE THREAD

**Issue by TheMomonga** [kanreisa/reichat#6]
こんにちは。
reichatの書きごこち、特に鉛筆がとても気に入りました。
要望なのですが、全消し、範囲消しを付けて頂けたら更に便利に使えると思いました。
ペンの太さももっと太くできたらと思います。
お時間のあるときにでもご検討頂けると嬉しいです。
今後のアップデートも楽しみにしております。
では、失礼致します。

**Comment by kanreisa** [comment]
実装完了後お知らせいたします！

**Comment by kanreisa** [comment]
@TheMomonga かなり時間がたってしまいましたが、実装しました。ぜひお試しください。
- なお全消しはチャットコマンド `/clear` として実装しました。

**Comment by TheMomonga** [comment]
こんばんは、お忙しい中の更新お疲れ様です、早速確認させていただきました。
範囲、全消し共に動作しており、感謝しております。
鉛筆ツールの書き味がとても好みのお絵かきチャットなので、今後も楽しく使えそうです。
ありがとうございました。
