### ISSUE TITLE
very laggy in chrome/firefox

### ISSUE THREAD

**Issue by Meedle** [kanreisa/reichat#7]
Are there any plans to optimize it with either of these browsers?

**Comment by kanreisa** [comment]
please tell me more your environment profile
OS, CPU, GPU, Tablet, .. etc

**Comment by Meedle** [comment]
https://i.gyazo.com/f8065cd7ddd9c9844748b751dbe07e39.png 
Here's a Speccy run I did.

My tablet is a Wacom Intuos Pen Small Tablet (CTL480) (Old Version) 
http://www.amazon.com/Wacom-Intuos-Tablet-CTL480-Version/dp/B00EN27TCI/ Here's what it looks like.

It seems to lag in Microsoft Edge, as well, so it may be my computer or tablet.

**Comment by kanreisa** [comment]
> Intel HD Graphics 4000
> That's why laggy drawing stroke.

Maybe, you can optimize on here: `chrome://flags`

and this is recommended settings
![](https://yabumi.cc/1513184b5e1d81bebd80cb88.png)

For the time being, This is recommended.
https://github.com/kanreisa/reichat#designed-for

**Comment by Meedle** [comment]
Okay. Thank you! This has helped with the lag in both Chrome and Microsoft Edge a lot!
